export const card: string
export const cardList: string
export const container: string
export const description: string
export const highlight: string
export const introList: string
export const reshowOpeningBtn: string
export const title: string
export const wrapper: string
