export const menuBtn: string
export const menuBtnActive: string
export const menuBtnWrapper: string
export const menuLink: string
export const menuLinkActive: string
export const menuLinks: string
export const menuOverlay: string
export const menuOverlayActive: string
export const topLink: string
export const topLinkWrapper: string
