export const account: string
export const accountDesc: string
export const accountDescLabel: string
export const accountDescP: string
export const accountImage: string
export const carrier: string
export const carrierDescription: string
export const carrierTitle: string
export const star: string
export const starContainer: string
export const starName: string
