export const container: string
export const containerLeft: string
export const containerRight: string
export const descContainer: string
export const descContainerLeft: string
export const descContainerRight: string
export const description: string
export const imgContainerLeft: string
export const imgContainerRight: string
export const linkCard: string
export const linkCardDescription: string
export const title: string
